create temp table admissionlabs as
WITH pivoted AS (
    SELECT
          patientunitstayid,
          min(albumin) AS min_albumin,
          max(albumin) AS max_albumin,
          avg(albumin) AS mean_albumin,
          min(bilirubin) AS min_bilirubin,
          max(bilirubin) AS max_bilirubin,
          avg(bilirubin) AS mean_bilirubin,
          min(BUN) AS min_BUN,
          max(BUN) AS max_BUN,
          avg(BUN) AS mean_BUN,
          min(calcium) AS min_calcium,
          max(calcium) AS max_calcium,
          avg(calcium) AS mean_calcium,
          min(creatinine) AS min_creatinine,
          max(creatinine) AS max_creatinine,
          avg(creatinine) AS mean_creatinine,
          min(glucose) AS min_glucose,
          max(glucose) AS max_glucose,
          avg(glucose) AS mean_glucose,
          min(bicarbonate) AS min_bicarbonate,
          max(bicarbonate) AS max_bicarbonate,
          avg(bicarbonate) AS mean_bicarbonate,
          min(TotalCO2) AS min_TotalCO2,
          max(TotalCO2) AS max_TotalCO2,
          avg(TotalCO2) AS mean_TotalCO2,
          min(hematocrit) AS min_hematocrit,
          max(hematocrit) AS max_hematocrit,
          avg(hematocrit) AS mean_hematocrit,
          min(hemoglobin) AS min_hemoglobin,
          max(hemoglobin) AS max_hemoglobin,
          avg(hemoglobin) AS mean_hemoglobin,
          min(INR) AS min_INR,
          max(INR) AS max_INR,
          avg(INR) AS mean_INR,
          min(lactate) AS min_lactate,
          max(lactate) AS max_lactate,
          avg(lactate) AS mean_lactate,
          min(platelets) AS min_platelets,
          max(platelets) AS max_platelets,
          avg(platelets) AS mean_platelets,
          min(potassium) AS min_potassium,
          max(potassium) AS max_potassium,
          avg(potassium) AS mean_potassium,
          min(ptt) AS min_ptt,
          max(ptt) AS max_ptt,
          avg(ptt) AS mean_ptt,
          min(sodium) AS min_sodium,
          max(sodium) AS max_sodium,
          avg(sodium) AS mean_sodium,
          min(wbc) AS min_wbc,
          max(wbc) AS max_wbc,
          avg(wbc) AS mean_wbc,
          min(bands) AS min_bands,
          max(bands) AS max_bands,
          avg(bands) AS mean_bands,
          min(alt) AS min_alt,
          max(alt) AS max_alt,
          avg(alt) AS mean_alt,
          min(ast) AS min_ast,
          max(ast) AS max_ast,
          avg(ast) AS mean_ast,
          min(alp) AS min_alp,
          max(alp) AS max_alp,
          avg(alp) AS mean_alp,

    FROM `physionet-data.eicu_crd_derived.pivoted_lab` AS al
    WHERE al.chartoffset <= 360
    GROUP BY al.patientunitstayid
)
SELECT
      vital.*,
    -- from pivoted_score table
      min_albumin,
      max_albumin,
      mean_albumin,
      min_bilirubin,
      max_bilirubin,
      mean_bilirubin,
      min_BUN,
      max_BUN,
      mean_BUN,
      min_calcium,
      max_calcium,
      mean_calcium,
      min_creatinine,
      max_creatinine,
      mean_creatinine,
      min_glucose,
      max_glucose,
      mean_glucose,
      min_bicarbonate,
      max_bicarbonate,
      mean_bicarbonate,
      min_TotalCO2,
      max_TotalCO2,
      mean_TotalCO2,
      min_hematocrit,
      max_hematocrit,
      mean_hematocrit,
      min_hemoglobin,
      max_hemoglobin,
      mean_hemoglobin,
      min_INR,
      max_INR,
      mean_INR,
      min_lactate,
      max_lactate,
      mean_lactate,
      min_platelets,
      max_platelets,
      mean_platelets,
      min_potassium,
      max_potassium,
      mean_potassium,
      min_ptt,
      max_ptt,
      mean_ptt,
      min_sodium,
      max_sodium,
      mean_sodium,
      min_wbc,
      max_wbc,
      mean_wbc,
      min_bands,
      max_bands,
      mean_bands,
      min_alt,
      max_alt,
      mean_alt,
      min_ast,
      max_ast,
      mean_ast,
      min_alp,
      max_alp,
      mean_alp,

FROM vital
LEFT JOIN pivoted
    ON vital.patientunitstayid = pivoted.patientunitstayid
;
