CREATE temp TABLE cancer_diagnosis AS
WITH pivoted AS (
SELECT
    patientunitstayid,
    STRING_AGG(diagnosisstring) AS cancer_diagnosis,

    FROM `physionet-data.eicu_crd.diagnosis` AS admitcancer
    WHERE diagnosisstring LIKE '%renal|electrolyte imbalance|hyponatremia|due to elevated ADH levels|from tumor other than lung%'
    OR diagnosisstring LIKE '%renal|electrolyte imbalance|hypocalcemia|due to tumor lysis%'
    OR diagnosisstring LIKE '%renal|electrolyte imbalance|hyperkalemia|due to tumor lysis%'
    OR diagnosisstring LIKE '%renal|electrolyte imbalance|hypercalcemia|due to malignancy%'
    OR diagnosisstring LIKE '%renal|abnormality of urine quantity or quality|diabetes insipidus|central|from primary or metastatic tumor%'
    OR diagnosisstring LIKE '%pulmonary|disorders of vasculature|pulmonary hemorrhage|due to neoplasm%'
    OR diagnosisstring LIKE '%pulmonary|disorders of lung parenchyma|malignancy|primary lung cancer|squamous cell CA%'
    OR diagnosisstring LIKE '%pulmonary|disorders of lung parenchyma|malignancy|primary lung cancer|small cell CA%'
    OR diagnosisstring LIKE '%pulmonary|disorders of lung parenchyma|malignancy|primary lung cancer|poorly-differentiated%'
    OR diagnosisstring LIKE '%pulmonary|disorders of lung parenchyma|malignancy|primary lung cancer|mesothelioma%'
    OR diagnosisstring LIKE '%pulmonary|disorders of lung parenchyma|malignancy|primary lung cancer|large cell CA%'
    OR diagnosisstring LIKE '%pulmonary|disorders of lung parenchyma|malignancy|primary lung cancer|bronchoalveolar cell CA%'
    OR diagnosisstring LIKE '%pulmonary|disorders of lung parenchyma|malignancy|primary lung cancer|biopsy pending%'
    OR diagnosisstring LIKE '%pulmonary|disorders of lung parenchyma|malignancy|primary lung cancer|adenocarcinoma%'
    OR diagnosisstring LIKE '%pulmonary|disorders of lung parenchyma|malignancy|primary lung cancer%'
    OR diagnosisstring LIKE '%pulmonary|disorders of lung parenchyma|malignancy|lymphoma%'
    OR diagnosisstring LIKE '%pulmonary|disorders of lung parenchyma|malignancy|cancer with metastases to the lung%'
    OR diagnosisstring LIKE '%pulmonary|disorders of lung parenchyma|malignancy%'
    OR diagnosisstring LIKE '%pulmonary|disorders of lung parenchyma|interstitial lung disease|hematological malignancy%'
    OR diagnosisstring LIKE '%oncology|skin, muscle and skeletal tumors|squamous cell CA%'
    OR diagnosisstring LIKE '%oncology|skin, muscle and skeletal tumors|soft tissue sarcoma|Kaposi%'
    OR diagnosisstring LIKE '%oncology|skin, muscle and skeletal tumors|soft tissue sarcoma%'
    OR diagnosisstring LIKE '%oncology|skin, muscle and skeletal tumors|melanoma|superficial spreading%'
    OR diagnosisstring LIKE '%oncology|skin, muscle and skeletal tumors|melanoma|nodular%'
    OR diagnosisstring LIKE '%oncology|skin, muscle and skeletal tumors|melanoma|lentigo maligna melanoma%'
    OR diagnosisstring LIKE '%oncology|skin, muscle and skeletal tumors|melanoma|acral lentiginous melanoma%'
    OR diagnosisstring LIKE '%oncology|skin, muscle and skeletal tumors|melanoma%'
    OR diagnosisstring LIKE '%oncology|skin, muscle and skeletal tumors|leiomyosarcoma%'
    OR diagnosisstring LIKE '%oncology|skin, muscle and skeletal tumors|bone tumors|osteosarcoma%'
    OR diagnosisstring LIKE '%oncology|skin, muscle and skeletal tumors|bone tumors|ewings sarcoma%'
    OR diagnosisstring LIKE '%oncology|skin, muscle and skeletal tumors|bone tumors|chondrosarcoma%'
    OR diagnosisstring LIKE '%oncology|skin, muscle and skeletal tumors|bone tumors|bony metastasis%'
    OR diagnosisstring LIKE '%oncology|skin, muscle and skeletal tumors|bone tumors%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|multiple myeloma%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|lymphoproliferative disease|non-Hodgkins lymphoma%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|lymphoproliferative disease|Hodgkins disease|nodular sclerosis%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|lymphoproliferative disease|Hodgkins disease|mixed cellularity%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|lymphoproliferative disease|Hodgkins disease|lymphocyte predominance%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|lymphoproliferative disease|Hodgkins disease|lymphocyte depleted%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|lymphoproliferative disease|Hodgkins disease%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|lymphoproliferative disease%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|unspecified%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|chronic myelogenous|without Philadelphia chromosome%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|chronic myelogenous|with Philadelphia chromosome%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|chronic myelogenous%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|chronic lymphocytic%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|acute myelogenous|M7%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|acute myelogenous|M6%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|acute myelogenous|M5%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|acute myelogenous|M4%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|acute myelogenous|M3%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|acute myelogenous|M2%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|acute myelogenous|M1%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|acute myelogenous|M0%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|acute myelogenous%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|acute lymphocytic|L3%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|acute lymphocytic|L2%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|acute lymphocytic|L1%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia|acute lymphocytic%'
    OR diagnosisstring LIKE '%oncology|hematologic malignancy|leukemia%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|nose tumor|squamous cell CA%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|nose tumor|nasopharyngeal CA%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|nose tumor|craniopharyngioma%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|neck tumor|thyroid tumor|papillary CA%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|neck tumor|thyroid tumor|medullary CA%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|neck tumor|thyroid tumor|follicular CA%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|neck tumor|thyroid tumor|anaplastic CA%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|neck tumor|thyroid tumor%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|neck tumor|other ill-defined sites%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|neck tumor|oro/hypopharyngeal CA%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|neck tumor|laryngeal CA%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|neck tumor%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|mouth and jaw tumor|oral cavity squamous cell CA%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|mouth and jaw tumor|lip squamous cell CA%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|mouth and jaw tumor%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|eye tumor|right%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|eye tumor|retinoblastoma%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|eye tumor|melanoma%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|eye tumor|left%'
    OR diagnosisstring LIKE '%oncology|head and neck tumors|eye tumor%'
    OR diagnosisstring LIKE '%oncology|GU tumors|uterine CA|uterine body%'
    OR diagnosisstring LIKE '%oncology|GU tumors|uterine CA|choriocarcinoma%'
    OR diagnosisstring LIKE '%oncology|GU tumors|uterine CA|adnexa%'
    OR diagnosisstring LIKE '%oncology|GU tumors|uterine CA|adenocarcinoma%'
    OR diagnosisstring LIKE '%oncology|GU tumors|uterine CA%'
    OR diagnosisstring LIKE '%oncology|GU tumors|testicular CA|seminoma%'
    OR diagnosisstring LIKE '%oncology|GU tumors|testicular CA|nonseminoma%'
    OR diagnosisstring LIKE '%oncology|GU tumors|testicular CA%'
    OR diagnosisstring LIKE '%oncology|GU tumors|renal cell CA|right kidney%'
    OR diagnosisstring LIKE '%oncology|GU tumors|renal cell CA|left kidney%'
    OR diagnosisstring LIKE '%oncology|GU tumors|renal cell CA%'
    OR diagnosisstring LIKE '%oncology|GU tumors|prostate CA%'
    OR diagnosisstring LIKE '%oncology|GU tumors|ovarian CA|right ovary%'
    OR diagnosisstring LIKE '%oncology|GU tumors|ovarian CA|left ovary%'
    OR diagnosisstring LIKE '%oncology|GU tumors|ovarian CA%'
    OR diagnosisstring LIKE '%oncology|GU tumors|male genetalia CA%'
    OR diagnosisstring LIKE '%oncology|GU tumors|female genetalia CA%'
    OR diagnosisstring LIKE '%oncology|GU tumors|cervical CA%'
    OR diagnosisstring LIKE '%oncology|GU tumors|bladder CA%'
    OR diagnosisstring LIKE '%oncology|GI tumors|retroperitoneum/peritoneum CA%'
    OR diagnosisstring LIKE '%oncology|GI tumors|pancreatic tumor|pancreatic CA%'
    OR diagnosisstring LIKE '%oncology|GI tumors|pancreatic tumor|islet cell tumor%'
    OR diagnosisstring LIKE '%oncology|GI tumors|pancreatic tumor%'
    OR diagnosisstring LIKE '%oncology|GI tumors|liver CA|hepatocellular CA%'
    OR diagnosisstring LIKE '%oncology|GI tumors|liver CA|CA metastatic to liver%'
    OR diagnosisstring LIKE '%oncology|GI tumors|liver CA%'
    OR diagnosisstring LIKE '%oncology|GI tumors|intra-abdominal sarcoma%'
    OR diagnosisstring LIKE '%oncology|GI tumors|intestinal CA|lymphoma%'
    OR diagnosisstring LIKE '%oncology|GI tumors|intestinal CA|carcinoid tumor%'
    OR diagnosisstring LIKE '%oncology|GI tumors|intestinal CA|adenocarcinoma%'
    OR diagnosisstring LIKE '%oncology|GI tumors|intestinal CA%'
    OR diagnosisstring LIKE '%oncology|GI tumors|GI/peritoneum CA%'
    OR diagnosisstring LIKE '%oncology|GI tumors|gastric CA|gastric lymphoma%'
    OR diagnosisstring LIKE '%oncology|GI tumors|gastric CA|gastric adenocarcinoma%'
    OR diagnosisstring LIKE '%oncology|GI tumors|gastric CA%'
    OR diagnosisstring LIKE '%oncology|GI tumors|gallbladder CA%'
    OR diagnosisstring LIKE '%oncology|GI tumors|esophageal CA%'
    OR diagnosisstring LIKE '%oncology|GI tumors|colon CA|transverse colon%'
    OR diagnosisstring LIKE '%oncology|GI tumors|colon CA|sigmoid%'
    OR diagnosisstring LIKE '%oncology|GI tumors|colon CA|right hemicolon%'
    OR diagnosisstring LIKE 'oncology|GI tumors|colon CA|cecum%%'
    OR diagnosisstring LIKE '%oncology|GI tumors|colon CA%'
    OR diagnosisstring LIKE '%oncology|GI tumors|cholangiocarcinoma%'
    OR diagnosisstring LIKE '%oncology|GI tumors|anal CA%'
    OR diagnosisstring LIKE '%oncology|GI tumors|abdominal carcinomatosis%'
    OR diagnosisstring LIKE '%oncology|CNS tumors|spinal cord tumors%'
    OR diagnosisstring LIKE '%oncology|CNS tumors|brain tumor|oligodendroglioma%'
    OR diagnosisstring LIKE '%oncology|CNS tumors|brain tumor|metastatic brain tumor%'
    OR diagnosisstring LIKE '%oncology|CNS tumors|brain tumor|meningioma%'
    OR diagnosisstring LIKE '%oncology|CNS tumors|brain tumor|glioblastoma multiforme%'
    OR diagnosisstring LIKE '%oncology|CNS tumors|brain tumor|ependymoma%'
    OR diagnosisstring LIKE '%oncology|CNS tumors|brain tumor|CNS lymphoma%'
    OR diagnosisstring LIKE '%oncology|CNS tumors|brain tumor|brain tumor - type unknown%'
    OR diagnosisstring LIKE '%oncology|CNS tumors|brain tumor|astrocytoma, low-grade%'
    OR diagnosisstring LIKE '%oncology|CNS tumors|brain tumor|astrocytoma, high-grade%'
    OR diagnosisstring LIKE '%oncology|CNS tumors|brain tumor%'
    OR diagnosisstring LIKE '%oncology|chest tumors|primary lung cancer|squamous cell CA%'
    OR diagnosisstring LIKE '%oncology|chest tumors|primary lung cancer|small cell CA%'
    OR diagnosisstring LIKE '%oncology|chest tumors|primary lung cancer|poorly-differentiated%'
    OR diagnosisstring LIKE '%oncology|chest tumors|primary lung cancer|mesothelioma%'
    OR diagnosisstring LIKE '%oncology|chest tumors|primary lung cancer|carcinoid%'
    OR diagnosisstring LIKE '%oncology|chest tumors|primary lung cancer|bronchoalveolar cell CA%'
    OR diagnosisstring LIKE '%oncology|chest tumors|primary lung cancer|biopsy pending%'
    OR diagnosisstring LIKE '%oncology|chest tumors|primary lung cancer|adenocarcinoma%'
    OR diagnosisstring LIKE '%oncology|chest tumors|primary lung cancer%'
    OR diagnosisstring LIKE '%oncology|chest tumors|pleura%'
    OR diagnosisstring LIKE '%oncology|chest tumors|metastatic lung CA%'
    OR diagnosisstring LIKE '%oncology|chest tumors|mediastinal tumor|thymoma|malignant%'
    OR diagnosisstring LIKE '%oncology|chest tumors|mediastinal tumor|thymoma%'
    OR diagnosisstring LIKE '%oncology|chest tumors|mediastinal tumor|teratoma%'
    OR diagnosisstring LIKE '%oncology|chest tumors|mediastinal tumor|lymphoma%'
    OR diagnosisstring LIKE '%oncology|chest tumors|mediastinal tumor%'
    OR diagnosisstring LIKE '%oncology|chest tumors|breast CA|male%'
    OR diagnosisstring LIKE '%oncology|chest tumors|breast CA|female%'
    OR diagnosisstring LIKE '%oncology|chest tumors|breast CA%'
    OR diagnosisstring LIKE '%neurologic|disorders of vasculature|stroke|hemorrhagic stroke|into pre-existent CNS mass%'
    OR diagnosisstring LIKE '%neurologic|disorders of the spinal cord and peripheral nervous system|spinal cord compression|secondary to metastasis%'
    OR diagnosisstring LIKE '%neurologic|CNS mass lesions|brain tumor|with carcinomatous meningitis%'
    OR diagnosisstring LIKE '%neurologic|CNS mass lesions|brain tumor|oligodendroglioma%'
    OR diagnosisstring LIKE '%neurologic|CNS mass lesions|brain tumor|metastatic brain tumor%'
    OR diagnosisstring LIKE '%neurologic|CNS mass lesions|brain tumor|glioblastoma multiforme%'
    OR diagnosisstring LIKE '%neurologic|CNS mass lesions|brain tumor|CNS lymphoma%'
    OR diagnosisstring LIKE '%neurologic|CNS mass lesions|brain tumor|astrocytoma, low-grade%'
    OR diagnosisstring LIKE '%neurologic|CNS mass lesions|brain tumor|astrocytoma, high-grade%'
    OR diagnosisstring LIKE '%hematology|white blood cell disorders|neutropenia|from chemotherapy%'
    OR diagnosisstring LIKE '%hematology|white blood cell disorders|eosinophilia|from cancer%'
    OR diagnosisstring LIKE '%hematology|platelet disorders|thrombocytopenia|primary hematologic malignancy%'
    OR diagnosisstring LIKE '%hematology|platelet disorders|thrombocytopenia|due to non-hematologic malignancy (marrow metastas%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|tumor lysis syndrome%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|plasma cell disorders|multiple myeloma%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|plasma cell disorders|Bence-Jones proteinuria%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|plasma cell disorders%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|myeloproliferative disorder|myelofibrosis%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|myeloproliferative disorder|essential thrombocythemia (clinical)%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|myeloproliferative disorder|chronic myeloproliferative disorder (clinical)%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|myeloproliferative disorder%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|myelodysplastic syndrome|refractory anemia with ringed sideroblasts%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|myelodysplastic syndrome|refractory anemia with excess blasts in transformation%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|myelodysplastic syndrome|refractory anemia with excess blasts%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|myelodysplastic syndrome|refractory anemia%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|myelodysplastic syndrome|chronic myelomonocytic leukemia%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|myelodysplastic syndrome%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|lymphoproliferative disease|non-Hodgkins lymphoma%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|lymphoproliferative disease|Hodgkins disease|nodular sclerosis%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|lymphoproliferative disease|Hodgkins disease|mixed cellularity%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|lymphoproliferative disease|Hodgkins disease|lymphocyte predominance%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|lymphoproliferative disease|Hodgkins disease|lymphocyte depleted%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|lymphoproliferative disease|Hodgkins disease%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|lymphoproliferative disease%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia|chronic myelogenous|without Philadelphia chromosome%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia|chronic myelogenous|with Philadelphia chromosome%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia|chronic myelogenous%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia|chronic lymphocytic%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia|acute myelogenous|M6%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia|acute myelogenous|M5%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia|acute myelogenous|M4%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia|acute myelogenous|M3%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia|acute myelogenous|M2%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia|acute myelogenous|M1%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia|acute myelogenous|M0%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia|acute myelogenous%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia|acute lymphocytic|L3%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia|acute lymphocytic|L1%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia|acute lymphocytic%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|leukemia%'
    OR diagnosisstring LIKE '%hematology|oncology and leukemia|carcinomatosis%'
    OR diagnosisstring LIKE '%hematology|coagulation disorders|DIC syndrome|associated with M3 leukemia%'
    OR diagnosisstring LIKE '%gastrointestinal|GI bleeding / PUD|lower GI bleeding|due to malignancy%'
    OR diagnosisstring LIKE '%endocrine|pituitary and temperature regulation|central diabetes insipidus|from primary or metastatic tumor%'
    OR diagnosisstring LIKE '%endocrine|fluids and electrolytes|hyponatremia|due to elevated ADH levels|from tumor other than lung%'
    OR diagnosisstring LIKE '%endocrine|fluids and electrolytes|hypocalcemia|due to tumor lysis%'
    OR diagnosisstring LIKE '%endocrine|fluids and electrolytes|hyperkalemia|due to tumor lysis%'
    OR diagnosisstring LIKE '%endocrine|fluids and electrolytes|hypercalcemia|due to malignancy%'
    OR diagnosisstring LIKE '%endocrine|fluids and electrolytes|diabetes insipidus|central|from primary or metastatic tumor%'
    OR diagnosisstring LIKE '%endocrine|endocrine tumors|thyroid carcinoma%'
    OR diagnosisstring LIKE '%endocrine|endocrine tumors|pheochromocytoma|malignant%'
    OR diagnosisstring LIKE '%endocrine|endocrine tumors|carcinoid syndrome%'
    GROUP BY admitcancer.patientunitstayid
)
SELECT
      labs.*
    ,cancer_diagnosis

FROM labs
LEFT JOIN pivoted
    ON labs.patientunitstayid = pivoted.patientunitstayid;

